- id: 1
  title: Pasteles a la carta
  description: Pequeño, mediano, grande.... o del tamaño y sabor que prefieras.
  image: /bliss/assets/images/menu/frio.jpg
  price: Por cotización
  weight: 100
  maximum-quantity: 100
  category: Pasteles
#  url: https://dragonfruit.jekyll-themes.com #URL of the page where the product is present

- id: 2
  title: Pastel mini 4 pulgadas
  description: Ideal para un antojito. Tamaño personal.
  image: /bliss/assets/images/menu/frio.jpg
  price: 80
  weight: 100
  maximum-quantity: 100
  category: Pasteles


- id: 3
  title: Pastel chico 7 pulgadas
  description: Parfecto para un festejo íntimo.
  image: /bliss/assets/images/menu/frio.jpg
  price: 200
  weight: 100
  maximum-quantity: 100
  category: Pasteles

- id: 4
  title: Pastel mediano 10 pulgadas
  description: Para celebrar en compañía de tus seres más queridos.
  image: /bliss/assets/images/menu/frio.jpg
  price: 400
  weight: 100
  maximum-quantity: 5
  category: Pasteles

- id: 5
  title: Pastel grande doble de 10 pulgadas
  description: Alcanza hasta para 20 personas.
  image: /bliss/assets/images/menu/grande-doble.jpg
  price: 750
  weight: 100
  maximum-quantity: 100
  category: Pasteles

- id: 6
  title: Pasteles personalizados
  description: Un detalle único, para recordar cualquier ocasión especial
  image: /bliss/assets/images/menu/personalizado.jpg
  price: Por cotización
  weight: 100
  maximum-quantity: 100
  category: Pasteles

- id: 7
  title: Besitos de nuez
  description: Media docena
  image: /bliss/assets/images/menu/besitos-nuez.jpg
  price: 60
  weight: 200
  maximum-quantity: 100
  category: Galletas

- id: 8
  title: Canela
  description: Docena, con chispa de chocolate
  image: /bliss/assets/images/menu/canela.jpg
  price: 60
  weight: 120
  maximum-quantity: 100
  category: Galletas
  
- id: 9
  title: Mermelada
  description: Con un toque ducle.  Docena.
  image: /bliss/assets/images/menu/mermelada.jpg
  price: 110
  weight: 120
  maximum-quantity: 100
  category: Galletas
  
- id: 10
  title: Limón
  description: Media docena
  image: /bliss/assets/images/menu/frio.jpg
  price: 50
  weight: 120
  maximum-quantity: 100
  category: Galletas